# Generated by Django 6.0.4 on 2026-04-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_login_alter_user_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="login",
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
